// Post-build script: extracts hashed Vite asset URLs from dist/index.html
// and writes them to dist-server/ssr-assets.js as an ES module.
//
// This ensures the SSR document references the correct built assets
// (e.g. /assets/index-AbCd1234.js) instead of source paths like /src/main.jsx.
//
// We output a .js ES module (not JSON) to avoid import attribute compatibility
// issues with the Cloudflare Workers runtime.

import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const indexHtml = readFileSync(resolve(root, 'dist/index.html'), 'utf-8')

// Extract CSS link tags
const cssMatches = [...indexHtml.matchAll(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g)]
const cssHrefs = cssMatches.map((m) => m[1])

// Extract JS module script tags
const jsMatches = [...indexHtml.matchAll(/<script[^>]*type="module"[^>]*src="([^"]+)"[^>]*>/g)]
const jsSrcs = jsMatches.map((m) => m[1])

const assets = {
  css: cssHrefs,
  js: jsSrcs,
}

const jsContent = `// Auto-generated by scripts/extract-assets.js — do not edit.
// Contains hashed Vite asset URLs extracted from dist/index.html.
export default ${JSON.stringify(assets, null, 2)};
`

writeFileSync(
  resolve(root, 'dist-server/ssr-assets.js'),
  jsContent,
)

console.log('[extract-assets] Wrote dist-server/ssr-assets.js')
console.log(`  CSS: ${cssHrefs.join(', ') || '(none)'}`)
console.log(`  JS:  ${jsSrcs.join(', ') || '(none)'}`)
